### ISSUE TITLE
Can not start NanoSatMOSupervisorSim on branch master

### ISSUE THREAD

**Issue by fuchs257** [esa/nanosat-mo-framework#14]
Hi,
i can not get the NanoSatMOSupervisorSim running. Console output down below.
What i already tried is:
- changing version of JDBC in core/mo-services-impl/ccsds-com-impl/pom.xml to given versions in comments
- Start from within Netbeans IDE
- Start with generated nanosat-mo-supervisor-sim.sh

using
- openjdk 1.8.0_222
- ubunbtu 16.04

thanks for help

`Oct 09, 2019 1:47:59 AM esa.mo.helpertools.helpers.HelperMisc loadProperties
INFO: Loading properties file:/home/marius/repo/nanosat-mo-framework/sdk/sdk-package/target/nmf-sdk-2.0.0-SNAPSHOT/home/nmf/nanosat-mo-supervisor-sim/provider.properties
Oct 09, 2019 1:47:59 AM esa.mo.helpertools.helpers.HelperMisc loadProperties
INFO: Loading properties file:/home/marius/repo/nanosat-mo-framework/sdk/sdk-package/target/nmf-sdk-2.0.0-SNAPSHOT/home/nmf/nanosat-mo-supervisor-sim/settings.properties
Oct 09, 2019 1:47:59 AM esa.mo.helpertools.helpers.HelperMisc loadProperties
INFO: Loading properties file:/home/marius/repo/nanosat-mo-framework/sdk/sdk-package/target/nmf-sdk-2.0.0-SNAPSHOT/home/nmf/nanosat-mo-supervisor-sim/transport.properties
Oct 09, 2019 1:47:59 AM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
INFO: Creating a new instance of the database driver: org.sqlite.JDBC
Oct 09, 2019 1:47:59 AM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
SEVERE: null
java.lang.ClassNotFoundException: org.sqlite.JDBC
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at esa.mo.com.impl.archive.db.DatabaseBackend.startDatabaseDriver(DatabaseBackend.java:102)
	at esa.mo.com.impl.archive.db.DatabaseBackend.startBackendDatabase(DatabaseBackend.java:93)
	at esa.mo.com.impl.provider.ArchiveManager.init(ArchiveManager.java:114)
	at esa.mo.com.impl.provider.ArchiveProviderServiceImpl.init(ArchiveProviderServiceImpl.java:93)
	at esa.mo.com.impl.util.COMServicesProvider.init(COMServicesProvider.java:49)
	at esa.mo.nmf.nanosatmosupervisor.NanoSatMOSupervisor.init(NanoSatMOSupervisor.java:90)
	at esa.mo.nmf.provider.NanoSatMOSupervisorSoftSimImpl.init(NanoSatMOSupervisorSoftSimImpl.java:65)
	at esa.mo.nmf.provider.NanoSatMOSupervisorSoftSimImpl.main(NanoSatMOSupervisorSoftSimImpl.java:59)

Oct 09, 2019 1:47:59 AM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
INFO: Attempting to establish a connection to the database: jdbc:sqlite:comArchive.db
Oct 09, 2019 1:47:59 AM esa.mo.com.impl.archive.db.DatabaseBackend createEMFactory
INFO: Creating Entity Manager Factory...
Exception in thread "Archive_GeneralProcessor-thread-1" java.lang.NoClassDefFoundError: javax/persistence/Persistence
	at esa.mo.com.impl.archive.db.DatabaseBackend.createEMFactory(DatabaseBackend.java:153)
	at esa.mo.com.impl.archive.db.DatabaseBackend.access$000(DatabaseBackend.java:41)
	at esa.mo.com.impl.archive.db.DatabaseBackend$1.run(DatabaseBackend.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: javax.persistence.Persistence
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
Oct 09, 2019 1:47:59 AM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
INFO: There was an SQLException, maybe the comArchive.db folder/file does not exist. Attempting to create it...
Oct 09, 2019 1:47:59 AM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
INFO: Derby connection already exists! Error: {0}
java.sql.SQLException: No suitable driver found for jdbc:sqlite:comArchive.db;create=true
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at esa.mo.com.impl.archive.db.DatabaseBackend.startDatabaseDriver(DatabaseBackend.java:125)
	at esa.mo.com.impl.archive.db.DatabaseBackend.startBackendDatabase(DatabaseBackend.java:93)
	at esa.mo.com.impl.provider.ArchiveManager.init(ArchiveManager.java:114)
	at esa.mo.com.impl.provider.ArchiveProviderServiceImpl.init(ArchiveProviderServiceImpl.java:93)
	at esa.mo.com.impl.util.COMServicesProvider.init(COMServicesProvider.java:49)
	at esa.mo.nmf.nanosatmosupervisor.NanoSatMOSupervisor.init(NanoSatMOSupervisor.java:90)
	at esa.mo.nmf.provider.NanoSatMOSupervisorSoftSimImpl.init(NanoSatMOSupervisorSoftSimImpl.java:65)
	at esa.mo.nmf.provider.NanoSatMOSupervisorSoftSimImpl.main(NanoSatMOSupervisorSoftSimImpl.java:59)

Oct 09, 2019 1:47:59 AM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
INFO: Most likely there is another instance of the same application already running. Two instances of the same application are not allowed. The application will exit.`

**Comment by fuchs257** [comment]
problem does not occur on branch dev.

**Comment by yannickl96** [comment]
Hi @fuchs257 ,
we always recommend to use dev branch as it has the most recent stable patches, e.g. the fix for the problem you encountered.

Cheers!
