### ISSUE TITLE
Problem starting NMF Supervisor

### ISSUE THREAD

**Issue by misev** [esa/nanosat-mo-framework#5]
I've been following the guide at https://github.com/esa/nanosat-mo-framework/tree/master/sdk#running-the-sdk and while starting the supervisor I have the output below. Notably no Directory Service MAL URI is generated as far as I can see, and the providerURIs.properties file is empty.

Any hints on what the problem could be? I couldn't find anything about the error "Unknown transport factory for protocol: rmi"

```
nanosat-mo-supervisor-sim/nanosat-mo-supervisor-sim.sh 
Jun 24, 2019 12:56:31 PM esa.mo.helpertools.helpers.HelperMisc loadPropertiesFile
WARNING: The file provider.properties does not exist on the path: provider.properties
Jun 24, 2019 12:56:31 PM esa.mo.helpertools.helpers.HelperMisc loadPropertiesFile
WARNING: The file settings.properties does not exist on the path: settings.properties
Jun 24, 2019 12:56:31 PM esa.mo.helpertools.helpers.HelperMisc loadPropertiesFile
WARNING: The file transport.properties does not exist on the path: transport.properties
Jun 24, 2019 12:56:31 PM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
INFO: Creating a new instance of the database driver: org.sqlite.JDBC
Jun 24, 2019 12:56:31 PM esa.mo.com.impl.archive.db.DatabaseBackend createEMFactory
INFO: Creating Entity Manager Factory...
Jun 24, 2019 12:56:31 PM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
INFO: Attempting to establish a connection to the database: jdbc:sqlite:comArchive.db
Jun 24, 2019 12:56:31 PM esa.mo.nmf.nanosatmosupervisor.NanoSatMOSupervisor init
SEVERE: The services could not be initialized. Perhaps there's something wrong with the Transport Layer.
org.ccsds.moims.mo.mal.MALException: Unknown transport factory for protocol: rmi
	at org.ccsds.moims.mo.mal.transport.MALTransportFactory.newFactory(MALTransportFactory.java:143)
	at esa.mo.mal.impl.transport.TransportSingleton.internalInstance(TransportSingleton.java:190)
	at esa.mo.mal.impl.transport.TransportSingleton.instance(TransportSingleton.java:114)
	at esa.mo.mal.impl.ServiceComponentImpl.<init>(ServiceComponentImpl.java:107)
	at esa.mo.mal.impl.provider.MALProviderImpl.<init>(MALProviderImpl.java:63)
	at esa.mo.mal.impl.provider.MALProviderManagerImpl.createProvider(MALProviderManagerImpl.java:68)
	at esa.mo.helpertools.connections.ConnectionProvider.startService(ConnectionProvider.java:146)
	at esa.mo.com.impl.provider.ArchiveProviderServiceImpl.init(ArchiveProviderServiceImpl.java:100)
	at esa.mo.com.impl.util.COMServicesProvider.init(COMServicesProvider.java:49)
	at esa.mo.nmf.nanosatmosupervisor.NanoSatMOSupervisor.init(NanoSatMOSupervisor.java:90)
	at esa.mo.nmf.provider.NanoSatMOSupervisorSoftSimImpl.init(NanoSatMOSupervisorSoftSimImpl.java:65)
	at esa.mo.nmf.provider.NanoSatMOSupervisorSoftSimImpl.main(NanoSatMOSupervisorSoftSimImpl.java:59)

Jun 24, 2019 12:56:31 PM esa.mo.com.impl.archive.db.DatabaseBackend$1 run
INFO: The EntityManagerFactory was created.
```
Before this step I did the following:
```
$ export NMF_HOME=/home/dimitar/projects/tmp/nanosat-mo-framework
$ mvn install -P assembly-with-dependencies

# output was fine with exception of these errors which can be ignored according to the README

[ERROR] no module descriptor for int.esa.nmf.core.moservices:xml
[ERROR] no module descriptor for int.esa.nmf.core.moservices.api:software-management
[ERROR] no module descriptor for int.esa.nmf.core.moservices.api:platform
[ERROR] no module descriptor for int.esa.nmf.core:helper-tools
[ERROR] no module descriptor for int.esa.nmf.core.moservices.impl:ccsds-com
[ERROR] no module descriptor for int.esa.nmf.core.moservices.impl:ccsds-mc
[ERROR] no module descriptor for int.esa.nmf.core.moservices.impl:nmf-software-management
[ERROR] no module descriptor for int.esa.nmf.core.moservices.impl:nmf-platform-generic
[ERROR] no module descriptor for int.esa.nmf.core.moservices.impl:ccsds-common
[ERROR] no module descriptor for int.esa.nmf.core:generic-composite-model
[ERROR] no module descriptor for int.esa.nmf.core:generic-nanosat-monolithic
[ERROR] no module descriptor for int.esa.nmf.core:nanosat-mo-connector
[ERROR] no module descriptor for int.esa.nmf.core:generic-nanosat-mo-supervisor
[ERROR] no module descriptor for int.esa.nmf.core:ground-mo-adapter
[ERROR] no module descriptor for int.esa.nmf.core:generic-ground-mo-proxy
[ERROR] no module descriptor for int.esa.nmf.core:nmf-package-lib
```

**Comment by misev** [comment]
Forgot to mention, OS is Debian testing, Java is OpenJDK:

$ javac -version
javac 1.8.0_171

**Comment by yannickl96** [comment]
Hello @misev , Could you please tell me the files in your nanosat-mo-supervisor folder from which you run the supervisor?

**Comment by misev** [comment]
```
~/.../sdk/sdk-package/target$ ll
total 72168
drwxr-xr-x 2 dimitar dimitar     4096 Jun 24 12:10 antrun/
drwxr-xr-x 2 dimitar dimitar     4096 Jun 24 12:10 archive-tmp/
drwxr-xr-x 2 dimitar dimitar     4096 Jun 24 12:10 classes/
-rw-r--r-- 1 dimitar dimitar    36864 Jun 24 12:39 comArchive.db
drwxr-xr-x 2 dimitar dimitar     4096 Jun 24 12:10 dependency-maven-plugin-markers/
drwxr-xr-x 4 dimitar dimitar     4096 Jun 24 12:10 nmf-sdk-2.0.0-SNAPSHOT/
-rw-r--r-- 1 dimitar dimitar 73833357 Jun 24 12:10 nmf-sdk-2.0.0-SNAPSHOT.zip
-rw-r--r-- 1 dimitar dimitar        0 Jul  2 15:10 providerURIs.properties
```

**Comment by yannickl96** [comment]
Sorry, I meant the files in **sdk/sdk-package/target/nmf-sdk-2.0.0-SNAPSHOT/bin/space/nanosat-mo-supervisor/**. Your warnings are mentioning missing properties files.

**Comment by misev** [comment]
I tried again to start it from the directory where this script is (sdk/sdk-package/target/nmf-sdk-2.0.0-SNAPSHOT/bin/space/nanosat-mo-supervisor-sim) and somehow it worked now. I think this was not clear in the README, previously when I got the error I started it with an absolute path to the script.

**Comment by yannickl96** [comment]
Ah that may have been the problem. Java looks for the properties files in your current execution directory. So when you are outside of the nanosat-mo-supervisor folder it will not find them. Thanks for your feedback!
