### ISSUE TITLE
Problem running demos

### ISSUE THREAD

**Issue by dragikamov** [esa/nanosat-mo-framework#7]
I have been following https://opssat1.esoc.esa.int/dmsf/files/35/view on how to build the framework and run the demos. Running any of the demos causes the following output from Netbeans:
```
cd /home/dragikamov/Desktop/nanosat-mo-framework/sdk/examples/space/hello-world-full; JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 /home/dragikamov/netbeans-8.2/java/maven/bin/mvn "-Dexec.args=-classpath %classpath esa.mo.nmf.apps.DemoHelloWorldFull" -Dexec.executable=/usr/lib/jvm/java-8-openjdk-amd64/bin/java org.codehaus.mojo:exec-maven-plugin:1.2.1:exec
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
Inspecting build with total of 1 modules...
Not installing Nexus Staging features:
 * Preexisting staging related goal bindings found in 1 modules.
                                                                        
------------------------------------------------------------------------
Building ESA NMF SDK App Example - Hello World Full 2.0.0-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ hello-world-full ---
Jun 27, 2019 9:19:33 PM esa.mo.helpertools.helpers.HelperMisc loadPropertiesFile
WARNING: The file provider.properties does not exist on the path: provider.properties
Jun 27, 2019 9:19:33 PM esa.mo.helpertools.helpers.HelperMisc loadPropertiesFile
WARNING: The file settings.properties does not exist on the path: settings.properties
Jun 27, 2019 9:19:33 PM esa.mo.helpertools.helpers.HelperMisc loadPropertiesFile
WARNING: The file transport.properties does not exist on the path: transport.properties
Jun 27, 2019 9:19:33 PM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
INFO: Creating a new instance of the database driver: org.sqlite.JDBC
Jun 27, 2019 9:19:33 PM esa.mo.com.impl.archive.db.DatabaseBackend createEMFactory
INFO: Creating Entity Manager Factory...
Jun 27, 2019 9:19:33 PM esa.mo.com.impl.archive.db.DatabaseBackend startDatabaseDriver
INFO: Attempting to establish a connection to the database: jdbc:sqlite:comArchive.db
Jun 27, 2019 9:19:33 PM esa.mo.nmf.nanosatmoconnector.NanoSatMOConnectorImpl init
SEVERE: The services could not be initialized. Perhaps there's something wrong with the Transport Layer.
org.ccsds.moims.mo.mal.MALException: Unknown transport factory for protocol: rmi
	at org.ccsds.moims.mo.mal.transport.MALTransportFactory.newFactory(MALTransportFactory.java:143)
	at esa.mo.mal.impl.transport.TransportSingleton.internalInstance(TransportSingleton.java:190)
	at esa.mo.mal.impl.transport.TransportSingleton.instance(TransportSingleton.java:114)
	at esa.mo.mal.impl.ServiceComponentImpl.<init>(ServiceComponentImpl.java:107)
	at esa.mo.mal.impl.provider.MALProviderImpl.<init>(MALProviderImpl.java:63)
	at esa.mo.mal.impl.provider.MALProviderManagerImpl.createProvider(MALProviderManagerImpl.java:68)
	at esa.mo.helpertools.connections.ConnectionProvider.startService(ConnectionProvider.java:146)
	at esa.mo.com.impl.provider.ArchiveProviderServiceImpl.init(ArchiveProviderServiceImpl.java:100)
	at esa.mo.com.impl.util.COMServicesProvider.init(COMServicesProvider.java:49)
	at esa.mo.nmf.nanosatmoconnector.NanoSatMOConnectorImpl.init(NanoSatMOConnectorImpl.java:116)
	at esa.mo.nmf.apps.DemoHelloWorldFull.<init>(DemoHelloWorldFull.java:54)
	at esa.mo.nmf.apps.DemoHelloWorldFull.main(DemoHelloWorldFull.java:65)
```
Any suggestions on how to continue? 

I cloned the master repo and I am building and running this on Ubuntu 19.04 with javac 1.8.0_212 and NetBeans 8.2. 

This might look similar to [Dimitar's issue](https://github.com/esa/nanosat-mo-framework/issues/5), but I managed to run `nanosat-mo-supervisor-sim.sh` and `consumer-test-tool.sh` and still the same error occurs when running the demo.

**Comment by yannickl96** [comment]
Hello @dragikamov !
Could you try to run the app from the supervisor with simulator? You can see how to do this from this tutorial at https://nanosat-mo-framework.readthedocs.io/en/latest/sdk.html .
Please let me know if you encounter any problems while doing that.

**Comment by dragikamov** [comment]
Yes @yannickl96, it works. Thank you.
